# Setup reference: https://dashboard.ngrok.com/get-started/setup/docker

version: '3.9'

networks:
  ngrokTest:

services:
  api:
    image: myAppImage
    container_name: api
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - ngrokTest

  ngrok:
    image: ngrok/ngrok:3.22.0-alpine-amd64
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2tbGpvEZks9ix3D5JK8QgGkP8Dj_5JuiWTKCFwkiWMFNgYv2g
    command: https://dashboard.ngrok.com/get-started/setup/docker
    
