---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#pick one of the weather providers
environment:
  - PASSWORD: "MIIJJwIBAAKCAgEAvzRBCR+uNV8Ml6rfXv6RrE5ej0+YRBY4vnVfR0g7R8rzbfR2
GmmkJze4su299jo9PBCsztJxT3dvlaQUGD5haokozQKRNWHMmCcIffMrT1+0tuxn
O5+9wFx1S8AcdHjfvtSHfbhXM1gXnJJuNJ2tg3c7LY1b1oB4iI0fwv7NIm5294gw
9eVi8NaaNOpfd/jZdVCv7C5G8E7z/xHpCoRPggp7Q01vaD/kg9jDOZjfuPY5LIi7
q3IpXKGwwE7RVngHdJT41osT01cNZbnK+P39nlG/Xfb4bpEv1PIfn98kIGtxi9j+
JoTBTprpmopoEjm8HlgIqGRhRQf3V2KNuFThGsXsKAcVxgCQUWbVHD0nNbVC3A+e
QBjgCUqjKZ/e69hZajpU/3+2/U6jPQSzvWPLF74UCQBM3tzHz2fyGhGJBUt/es96
l3MEzzs7hkeIoaqc1x9papHodoCWi07ijqNjXe7XZfMsO4DN4Vmu8wzUVQ80Wngy
JiiOompovkYeJ69sdRgNLXD39YOYGGaEYw31cv/v6a44KtcPS3ybtaHG54y9oFsk
3iRgAV9MSjPH6mdRazT2rWG8MpB2i2op86TniV7zIHEOdgJeObKEhw/3T17JC4Ve
X+CAZ6p89FND/545XKPZ6NbtU4+gFjjGC6WYWW1WlHdwy3T9YNLFd4eDWdsCAwEA
AQKCAf9r7JLJE5jBh2UUNt7eP9L570JwofzQcbqVxqqBEcRkQaol5lbDkd2WRV17
obYXxcfKn57rHt3WfRP+4x50kMFr4P+muEw+VXWmbGHeteM8akkW91lNzlzMt2N9
3nIxTAj/LfdMf0C5OoAZYI3UJSxLiIFetOuhp+JhMUc8SZaAWNnN3pHEOjYeuwNP
2vsIPO6ByYmDRpvECMywrOtdhFFclY397zdzIJ1bzn5jhGbDgDfFa2iC3W17W8jo
w5Rlulp685uBff8yy3BEexqWcMc3Fe1unHid8FWPXRt8ofdCVWNCDLloBIcYV1iE
YptbrjsA5a/9XKuKy3RRXs+fvElSWaFGe0Mg3iwvItEwG9Ztud+eAWPOUryUUmUZ
AcqQq2laSbjO0VeXOuWdLjrEUmxKT3kXKTaBeJ0wMxweD2L1ahHl7y0awe5JUf7U
XwFKckk0UglrcbDUGYq1z2r9cBVaOW53+oLpLcL6Y45qyKumPK2P0/4yVrdh9ZDL
KdGu0mrBk59tlofXtt0HBGf/VdOgGR7ep24Sjo+r1PrEdr09hTjXJ+uJid5aHJ68
aPIeyLbAt0JpOQWG64QhUunfysJz2BZhL3mJdnkZWHPrKsj4ZNTCKRRm0onz7ih8
1BUv+OXFrmOrxYJ3dpZZxRyrchz4vFM/VIB09PD2b4lH4XahAoIBAQDeiPAwuyAw
VF4T5S1kkiV04z6qscTwhARoeyLsEAggjpNXP87d5PrB/kqNqko/a3mMnqX/p0pz
oNxahh0fMOHIEXuEIgprP3TmdqLs/JNDffuT1ujObDYUMeGTEfxlsikDiiEDfo/4
tVbOQFFC464ZaGjLWYZ87GH2I7B4x3nOlMlVFgf2N3uH2HcTblGUrGIARgyJ1roy
WoUmiAXM/rGAcHNfC62wjf/GsJK4an/lcJp9sKzF5XcP5RKKjOpH0aROV4+7MpnL
T2Iev2Jibw1xczzJt+Y4BLj4R2a9P9ICVQC52b4Bgp2IDe0SWoLSERkQiHCYk2gA
q92T1s4J2YchAoIBAQDb9Sex+CC2AyqVXvi4pdPnQcZbKtJ5x2AEv6SNB3QswtPg
Sw4D4TsdDb/WGJoGziVPHBhbWRq6b028SOEvdVZbhHmHcw55+mx9BGaww5NcWtNi
ZcpvIy/2z0wZe+MbA/V7L7IM8hLVvekPW3zeKJOi1gtaXlZyNcpUeN5yyTizfS38
wf0+lvdVvItkCMFSnw9cPPc64XtL41GZIa8LsNF9wJP0jON1wkFo0ugmATzseDld
yODARsnHW1lEhMTKsHqVaK11c9N3tGEzH+oAcBjc20ulyq76+BgpmOjZNqQ13381
AjNoJE9SxPtXNLiO0c5cR4bOeo4L+RL3LvFjis17AoIBAED+k9BXxvX2nieHZvOZ
r7Ds8g+erhtlI3h0hmWV5RnFKolwDHZIe2iPYazwkJDnTe/hIjCB5r/QuqsBwp2q
hDcPzBhybMKYHQd2nO1Ec6phsEmkmgg4GK9bRjvTI/l7yHjNLgk8PMZyCDFjHZjA
sMeg9AJ4WkxAKfhewhr0f8HzOL5OGfMyjzTE5zpYnSEkG9diniTf/y/Xuk3fqnoN
5T/TGA8pdQg84Phh9+g+yq3zblvJbxy5gUW2LO0kbQSe2TM8ZbFR/RMhU1IRqaWA
M9fvxVBREr9HudJh4ELj0e12cCjXzKPaRzJGhvg2UUETV1O51dDqNJUFnUihkznT
O6ECggEBANgRWK8QaUGilqAorPblnuUazbkctaj+2ymPABuxaMPXlr5LvDa/d4ww
x3OOsy9gLXIqzRpey0y8rYX5qYsvHmfEGIWf1maoQw4D1sRpOkaMyf1stJC75g/y
znRyKEOPfgNGdQcWfL4OUfTOEDlDbtOUo45gAVcr09dq7EmhtNtManJSNWzYa5qD
HgJkP1Pj//jBwrLKcI25fZyJZCR9yyxWkoC2LXKuIgbQt08uBCTebKvd+jmmz+vP
pj8SlSXuelxueYZZAzAhtyG7hehsNWAu4363PXA3abTjCkjlziVFqPXvdYQltu49
phCiL3HMU4R+lsQZy5OjVqgOKv13iiUCggEAVGyIDm27jyym4/bv+z3DUMRF2pPd
KBb3UosgJ0KOaxHoZPYvMI54kCd8apUpS3vnYHd5uirTFjSIlN7Nghb7Op6gW3HY
2FWXYF/eyg6HomO+sswTTft/xl5jBE09OFcXlxp23z5u28iMD8SRcXN4clG4aJUP
+pENOLZNq0IwaZu86Gr6cBcyF+6I7zhNzY0e2ezShGt9JKWmvI4HpAsNjQvvZWmi
iuN7OoFttzJbgWHrhTAUaJAPm8EaPpmEuFVAsDVVL3KVLSSbYY33+H80+p/KwpRA
n/F+o1X8RrzgGMJcwO65ZlngrZIXSF1Zd7DWL6l8M08oYBaTmRnot+FiyQ=="  # Certifique-se de que está entre aspas
providers:
  openweathermap: "20A8f6kgTewGVV3SPghwUfOteQavTk1F"
  weatherapi: "20A8f6kgTewGVV3SPghwUfOteQavTk1F"
color: gray
background:
  image: "https://th.bing.com/th/id/OIP.kQ3YK5S5MyzTF2wredIZwAHaEK?rs=1&pid=ImgDetMain"
  blur: sm
  #opacity: 65
title: "ChatGPT WEB"
favicon: "https://th.bing.com/th/id/OIP.kQ3YK5S5MyzTF2wredIZwAHaEK?rs=1&pid=ImgDetMain"
iconStyle: theme
headerStyle: underlined
hideVersion: true
target: _self
showStats: false
statusStyle: "dot"
website: "https://chat.openai.com"  # Adicionei o campo website aqui

layout:
  Management:
    style: row
    columns: 3
    icon: "/data/data/com.termux/files/home/downloads/favicon.ico"
  File Sharing:
    style: row
    columns: 3
    icon: "/data/data/com.termux/files/home/downloads/favicon.ico"
  Apps:
    style: row
    columns: 3
    icon: mdi-apps