---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#pick one of the weather providers
environment:
  - PASSWORD="20A8f6kgTewGVV3SPghwUfOteQavTk1F"  # Certifique-se de que está entre aspas
providers:
  openweathermap: 20A8f6kgTewGVV3SPghwUfOteQavTk1F
  weatherapi: 20A8f6kgTewGVV3SPghwUfOteQavTk1F
color: gray
background:
  image: /data/data/com.termux/files/home/downloads/favicon.ico
  blur: sm
  #opacity: 65
title: ChatGPT WEB
favicon:  /data/data/com.termux/files/home/downloads/favicon.ico
iconStyle: theme
headerStyle: underlined
hideVersion: true
target: _self
showStats: false
statusStyle: "dot"

layout:
  Management:
    style: row
    columns: 3
    icon: /data/data/com.termux/files/home/downloads/favicon.ico
  File Sharing:
    style: row
    columns: 3
    icon: /data/data/com.termux/files/home/downloads/favicon.ico
  Apps:
    style: row
    columns: 3
    icon: mdi-apps