name: CI Checks

on: push

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - name: 'Create env file'
        run: |
          echo DEPLOY_ENV=dev > .env
      - name: Install Dependencies 📥
        run: pnpm install --frozen-lockfile
      - name: Type Check 🧹
        run: pnpm run typecheck
      - name: Build website 📦
        run: pnpm run build 
        jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ 2b93c3a24618363a84e2607579de9e100782e656921a8a26ed813246c77b17e9 }}
          aws-secret-access-key: ${{ 2b93c3a24618363a84e2607579de9e100782e656921a8a26ed813246c77b17e9 }}
          aws-region: us-east-1  # Set your AWS region here
