name: CI Checks

on: push

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '7'  # Specify the version of pnpm you want to use
      - name: 'Create env file'
        run: |
          echo DEPLOY_ENV=dev > .env
      - name: Install Dependencies 📥
        run: pnpm install --frozen-lockfile
      - name: Type Check 🧹
        run: pnpm run typecheck
      - name: Build website 📦
        run: pnpm run build
        
